# Generated by Django 4.2 on 2026-04-10 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaRisco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Name of the risk area', max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Latitude coordinate', max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Longitude coordinate', max_digits=9)),
                ('nivel_risco', models.CharField(choices=[('baixo', 'Baixo'), ('medio', 'Médio'), ('alto', 'Alto')], default='baixo', help_text='Risk level classification', max_length=10)),
                ('descricao', models.TextField(blank=True, help_text='Optional description of the area')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp')),
            ],
            options={
                'verbose_name': 'Área de Risco',
                'verbose_name_plural': 'Áreas de Risco',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='RegistroMonitoramento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_agua', models.DecimalField(decimal_places=2, help_text='Water level measurement in meters', max_digits=5)),
                ('status', models.CharField(choices=[('normal', 'Normal'), ('alerta', 'Alerta'), ('critico', 'Crítico')], default='normal', help_text='Current monitoring status', max_length=10)),
                ('data_hora', models.DateTimeField(auto_now_add=True, help_text='Record timestamp')),
                ('area', models.ForeignKey(help_text='Risk area being monitored', on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='monitoramento.arearisco')),
            ],
            options={
                'verbose_name': 'Registro de Monitoramento',
                'verbose_name_plural': 'Registros de Monitoramento',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField(help_text='Alert message content')),
                ('nivel', models.CharField(choices=[('baixo', 'Baixo'), ('medio', 'Médio'), ('alto', 'Alto')], default='baixo', help_text='Alert severity level', max_length=10)),
                ('data_hora', models.DateTimeField(auto_now_add=True, help_text='Alert timestamp')),
                ('area', models.ForeignKey(help_text='Risk area that triggered the alert', on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='monitoramento.arearisco')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-data_hora'],
            },
        ),
    ]
