# Generated by Django 4.2 on 2026-05-26 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0002_arearisco_bairro_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='nivel',
            field=models.CharField(choices=[('baixo', 'Baixo'), ('medio', 'Médio'), ('alto', 'Alto'), ('critico', 'Crítico'), ('alerta', 'Alerta')], default='baixo', help_text='Alert severity level', max_length=10),
        ),
    ]
