# Generated by Django 4.2 on 2026-06-09 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0003_alter_alerta_nivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registromonitoramento',
            name='nivel_agua',
            field=models.DecimalField(decimal_places=2, help_text='Water level measurement in centimeters', max_digits=5),
        ),
    ]
