# Generated by Django 4.2 on 2026-06-09 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0004_alter_registromonitoramento_nivel_agua'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arearisco',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude coordinate', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='arearisco',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude coordinate', max_digits=9, null=True),
        ),
    ]
