# Generated by Django 4.2 on 2026-06-10 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0005_alter_arearisco_latitude_alter_arearisco_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='arearisco',
            name='cidade',
            field=models.CharField(default='Parauapebas', help_text='City where the area is located', max_length=100),
        ),
    ]
