# Generated by Django 4.2 on 2026-08-08 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0006_arearisco_cidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='resolvido',
            field=models.BooleanField(default=False, help_text='Whether the alert has been resolved'),
        ),
        migrations.AlterField(
            model_name='arearisco',
            name='foto',
            field=models.ImageField(blank=True, help_text='Optional image of the area', null=True, upload_to='areas/'),
        ),
    ]
