# Generated by Django 4.2 on 2026-08-31 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0007_alerta_resolvido_alter_arearisco_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='nivel',
            field=models.CharField(choices=[('baixo', 'Baixo'), ('medio', 'Médio'), ('alto', 'Alto'), ('critico', 'Crítico')], default='baixo', help_text='Alert severity level', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='arearisco',
            constraint=models.UniqueConstraint(fields=('nome', 'bairro', 'cidade'), name='unique_area_per_location'),
        ),
    ]
