# Generated by Django 5.2.17 on 2026-10-05 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0008_alter_alerta_nivel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='area',
            field=models.ForeignKey(help_text='Área de risco que gerou o alerta.', on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='monitoramento.arearisco', verbose_name='área'),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='data_hora',
            field=models.DateTimeField(auto_now_add=True, verbose_name='data e hora'),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='mensagem',
            field=models.TextField(help_text='Texto do alerta.', verbose_name='mensagem'),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='nivel',
            field=models.CharField(choices=[('baixo', 'Baixo'), ('medio', 'Médio'), ('alto', 'Alto'), ('critico', 'Crítico')], default='baixo', help_text='Gravidade do alerta.', max_length=10, verbose_name='nível'),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='resolvido',
            field=models.BooleanField(default=False, help_text='Marque quando o alerta já foi tratado.', verbose_name='resolvido'),
        ),
        migrations.AlterField(
            model_name='arearisco',
            name='bairro',
            field=models.CharField(blank=True, help_text='Bairro onde a área fica.', max_length=100, verbose_name='bairro'),
        ),
        migrations.AlterField(
            model_name='arearisco',
            name='cidade',
            field=models.CharField(default='Parauapebas', help_text='Cidade onde a área fica.', max_length=100, verbose_name='cidade'),
        ),
        migrations.AlterField(
            model_name='arearisco',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='data de cadastro'),
        ),
        migrations.AlterField(
            model_name='arearisco',
            name='descricao',
            field=models.TextField(blank=True, help_text='Descrição opcional da área.', verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='arearisco',
            name='foto',
            field=models.ImageField(blank=True, help_text='Foto opcional da área (até 5 MB).', null=True, upload_to='areas/', verbose_name='foto'),
        ),
        migrations.AlterField(
            model_name='arearisco',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude (preenchida pela busca de endereço ou pelo clique no mapa).', max_digits=9, null=True, verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='arearisco',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude (preenchida pela busca de endereço ou pelo clique no mapa).', max_digits=9, null=True, verbose_name='longitude'),
        ),
        migrations.AlterField(
            model_name='arearisco',
            name='nivel_risco',
            field=models.CharField(choices=[('baixo', 'Baixo'), ('medio', 'Médio'), ('alto', 'Alto')], default='baixo', help_text='Classificação de risco da área.', max_length=10, verbose_name='nível de risco'),
        ),
        migrations.AlterField(
            model_name='arearisco',
            name='nome',
            field=models.CharField(help_text='Nome da rua ou endereço da área de risco.', max_length=100, verbose_name='rua / endereço'),
        ),
        migrations.AlterField(
            model_name='registromonitoramento',
            name='area',
            field=models.ForeignKey(help_text='Área de risco monitorada.', on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='monitoramento.arearisco', verbose_name='área'),
        ),
        migrations.AlterField(
            model_name='registromonitoramento',
            name='data_hora',
            field=models.DateTimeField(auto_now_add=True, verbose_name='data e hora'),
        ),
        migrations.AlterField(
            model_name='registromonitoramento',
            name='nivel_agua',
            field=models.DecimalField(decimal_places=2, help_text='Nível de água medido, em centímetros.', max_digits=5, verbose_name='nível de água (cm)'),
        ),
        migrations.AlterField(
            model_name='registromonitoramento',
            name='status',
            field=models.CharField(choices=[('normal', 'Normal'), ('alerta', 'Alerta'), ('critico', 'Crítico')], default='normal', help_text='Calculado automaticamente: a partir de 80 cm = Crítico, a partir de 50 cm = Alerta.', max_length=10, verbose_name='status'),
        ),
    ]
